### ISSUE TITLE
py3: firstname/lastname returned as bytes instead of str

### ISSUE THREAD

**Issue by rumbin** [pyldap/pyldap#110] opened 2017-07-15 21:18 UTC
## Front matter
* I reported this issue at [Flask-AppBuilder/444](https://github.com/dpgaspar/Flask-AppBuilder/issues/444) but was sent here.
* We are authenticating against Microsoft AD Global Catalog, provided by Microsoft Server 2012 R2, which seems to be LDAPv3.
* pyldap==2.4.37

## Expected results
Querying `auth_ldap_firstname_field` and `auth_ldap_firstname_field` return firstname and lastname as strings.

## Actual results
The firstname and lastname fields are of type bytes. However, the email field is a string, as expected.

I tried all possible settings of bytes_mode, but with no success.

## Impact
When a new user registers in Superset (a Flask-Appbuilder app), the first- and lastname fields get populated with hex-encoded strings.

## Analysis
Adding a `.decode()` hotfixes the issue for me, but @dpgaspar from Flask-Appbuilder considers the root cause at pyldap.

**Comment by MartinBasti** [comment] 2017-07-17 08:08
I'm afraid that this is not a bug, but a design decision to return LDAP values as `bytes` in Py3. While in Py2 is possible to mixing bytes and string values as the same `str` type, in Py3 is clearly defined that bytes are bytes and must be decoded to string.

**Comment by rbarrois** [comment] 2017-07-17 13:32
Actually, it works the same in Py2.

The change between Py2 and Py3 occurs only on fields that are known (per the RFCs) to be UTF-8 encoded text : distinguished names, attribute names.

Attribute values can be anything: integers, raw UUID, custom encoding (for instance the SID number in Active Directory), profile pictures, etc.
=> We would have to parse the directory schema to get an idea of the type ("syntax" in LDAP speak) of each field, but that should be the job of a library built on top of pyldap / python-ldap.

In the issue Flask-AppBuilder issue, the code here is in cause: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L644

With ``bytes_mode=False`` (the recommended value with pyldap), you'll get:
```python
>>> new_user
{
  u'cn': [b'Rapha\xc3\xabl Barrois'],
  u'email': [b'rbarrois@example.org'],
}
```

With ``bytes_mode=True`` (for compatibility with python-ldap), you'd get:
```python
>>> new_user
{
  b'cn': [b'Rapha\xc3\xabl Barrois'],
  b'email': [b'rbarrois@example.org'],
}
```
Note that only the type of the attribute names change, never the values.


The Flask AppBuilder code doesn't seem to care about text vs. bytes; what is the expected type of parameters to the ``add_user`` function? Is it expected to work under Python2? Should it accept special characters?

The code there should be adapted to always decode the LDAP-provided value with an UTF-8 encoding, e.g:
```python
def ldap_extract(ldap_dict, field, fallback):
    if not ldap_dict.get(field):
        return fallback
    return ldap_dict[field][0].decode('utf-8') or fallback

user = self.add_user(
    username=username,
    first_name=ldap_extract(ldap_user_info, self.auth_ldap_firstname_field, username),
    last_name=ldap_extract(ldap_user_info, self.auth_ldap_lastname_field, username),
    email=ldap_extract(ldap_user_info, self.auth_ldap_email_field, username + '@email.notfound'),
    role=self.find_role(self.auth_user_registration_role)
)
```

**Comment by rumbin** [comment] 2017-07-17 19:13
Thank your very much for the detailed instructions!

**Comment by rbarrois** [comment] 2017-07-18 15:15
@rumbin you're welcome ;)

I'm closing this issue for now, feel free to reopen it if you need!

**Closed as completed by rbarrois** 2017-07-18 15:15 UTC
Labels: question
