### ISSUE TITLE
DN encoding problem

### ISSUE THREAD

**Issue by dershodan** [pyldap/pyldap#54] opened 2016-07-27 15:00 UTC
I have a User in my AD with the non-ascii character `ä` in the CN - therefore also in the DN.

Querying for this DN leads to the nasty `UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 10: ordinal not in range(128)`

Not sure this is a bug in your implementation, just figured it best to post it here as well as [here](http://stackoverflow.com/questions/38616020/pyldap-dn-encoding-error).

**Comment by rbarrois** [comment] 2016-07-27 21:37
That's a very weird bug, as `pyldap` is designed to avoid those issues.

How do you set up your connection, especially with regards to the `bytes_mode` flag?

**Comment by dershodan** [comment] 2016-07-28 06:12
Setting up the connection over VPN with 

```
con = ldap.initialize('ldap://10.0.1.15:389')
con.simple_bind(ldap_bind_name, ldap_bind_password)
```

I have never used the `bytes_mode` flag.

**Comment by rbarrois** [comment] 2016-07-28 10:31
In that case, what you see is expected.

When running under Python2, pyldap strives to be backwards-compatible with python-ldap, and behaves the same: expects bytes everywhere, returns bytes everywhere.

You should see many warnings in your console if you run your code with `python -Wdefault`.

In order to use pyldap's features, you need to explicitly set the `bytes_mode` flag on connection initalization, as described [in the dedicated README section](https://github.com/pyldap/pyldap#bytestext-management)

In your example snippet, simply update to:

``` python
con = ldap.initialize('ldap://10.0.1.15:389', bytes_mode=False)
con.simple_bind(ldap_bind_name, ldap_bind_password)
```

Then, your queries should work flowlessly :-)

Could you close the issue if this answer fixes your problem?

**Comment by dershodan** [comment] 2016-07-28 13:27
Thanks for your help - unfortunately the problem persists.

In this line the error occurs:
https://github.com/pyldap/pyldap/blob/master/Lib/ldap/ldapobject.py#L263

```
args
self = <ldap.ldapobject.SimpleLDAPObject instance at 0x7fe1467f1a70>
func = <built-in method search_ext of LDAP object at 0x7fe1482183c8>
args = (u'CN=Felix H\xe4usler,OU=Management,OU=UBERGRAPE,DC=UBERGRAPE,DC=local', 2, u'(objectClass=*)', None, 0, None, None, -1, 0)
kwargs = {}
```

What i did was run `dn.decode('utf-8')` over my DN parameter, which i had previously obtained as the result of another pyldap query.

To clarify - I get a group and use the `member` attributes to find attached users (over their DN). Respective code:

```
# tpl is one element obtained from a pyldap query
...
for m in tpl[1].get('member', []):
    object = self._get_single_element(m)
    ...

def _get_single_element(self, dn):
    ...
    return con.search_s(dn.decode('utf-8'), ldap.SCOPE_SUBTREE, u'(objectClass=*)')

```

**Comment by dershodan** [comment] 2016-07-29 08:30
Here another example for your convenience:

```
In [7]: import ldap

In [8]: con = ldap.initialize('ldap://10.0.1.15', bytes_mode=False)

In [9]: con.simple_bind(ldc.ldap_bind_name, ldc.ldap_bind_password)
Out[9]: 1

In [10]: con.search_s(u'CN=Felix Häusler,OU=Management,OU=UBERGRAPE,DC=UBERGRAPE,DC=local', ldap.SCOPE_BASE, u'objectClass=person')
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-10-d5573b3c33ff> in <module>()
----> 1 con.search_s(u'CN=Felix Häusler,OU=Management,OU=UBERGRAPE,DC=UBERGRAPE,DC=local', ldap.SCOPE_BASE, u'objectClass=person')

/home/vagrant/build/venv/local/lib/python2.7/site-packages/ldap/ldapobject.pyc in search_s(self, base, scope, filterstr, attrlist, attrsonly)
    766 
    767   def search_s(self,base,scope,filterstr='(objectClass=*)',attrlist=None,attrsonly=0):
--> 768     return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
    769 
    770   def search_st(self,base,scope,filterstr='(objectClass=*)',attrlist=None,attrsonly=0,timeout=-1):

/home/vagrant/build/venv/local/lib/python2.7/site-packages/ldap/ldapobject.pyc in search_ext_s(self, base, scope, filterstr, attrlist, attrsonly, serverctrls, clientctrls, timeout, sizelimit)
    759 
    760   def search_ext_s(self,base,scope,filterstr='(objectClass=*)',attrlist=None,attrsonly=0,serverctrls=None,clientctrls=None,timeout=-1,sizelimit=0):
--> 761     msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)
    762     return self.result(msgid,all=1,timeout=timeout)[1]
    763 

/home/vagrant/build/venv/local/lib/python2.7/site-packages/ldap/ldapobject.pyc in search_ext(self, base, scope, filterstr, attrlist, attrsonly, serverctrls, clientctrls, timeout, sizelimit)
    755       RequestControlTuples(serverctrls),
    756       RequestControlTuples(clientctrls),
--> 757       timeout,sizelimit,
    758     )
    759 

/home/vagrant/build/venv/local/lib/python2.7/site-packages/ldap/ldapobject.pyc in _ldap_call(self, func, *args, **kwargs)
    261     try:
    262       try:
--> 263         result = func(*args,**kwargs)
    264         if __debug__ and self._trace_level>=2:
    265           if func.__name__!="unbind_ext":

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 10: ordinal not in range(128)
```

**Comment by koniiiik** [comment] 2016-08-03 14:18
The problem lies here: https://github.com/pyldap/pyldap/blob/37fd75aa120317ef564ebf1beed99903f8fdd808/Modules/LDAPObject.c#L1130

In our case, on Python 2, `l_ldap_search_ext` gets called with the `base` argument being a `unicode` object containing non-ASCII characters. Pyldap goes to great lengths to ensure that it is indeed a `unicode` string, never a byte string, regardless of the Python version in use.

The problem is that the C-API format string `s` behaves differently in Python 2 vs. Python 3. On Python 3, a text string is always expected, and it is encoded using UTF-8 (as explained [here](https://docs.python.org/3.4/c-api/arg.html#strings-and-buffers)), whereas on Python 2, the same `s` format string encodes a `unicode` object using the default encoding, which is pretty much always ASCII ([docs](https://docs.python.org/2/c-api/arg.html)). (At least, on Linux, I haven't yet encountered a version of Python 2 where the default encoding wasn't ASCII.)

In our scenario, we can just slap a band-aid on this by doing the following:

``` diff
diff --git a/Modules/LDAPObject.c b/Modules/LDAPObject.c
index 1a46326..1b57800 100644
--- a/Modules/LDAPObject.c
+++ b/Modules/LDAPObject.c
@@ -1127,7 +1127,7 @@ l_ldap_search_ext( LDAPObject* self, PyObject* args )
     int msgid;
     int ldaperror;

-    if (!PyArg_ParseTuple( args, "sis|OiOOdi",
+    if (!PyArg_ParseTuple( args, "esis|OiOOdi", "utf-8",
                            &base, &scope, &filter, &attrlist, &attrsonly,
                            &serverctrls, &clientctrls, &timeout, &sizelimit )) return NULL;
     if (not_valid(self)) return NULL;
```

However, that only solves the immediate problem we have encountered, when the DN contains non-ASCII characters; it will still blow up if any of the other strings contains non-ASCII chars. A more comprehensive fix for this problem would be to either flip the handling of text- vs. bytestrings on the Python side, and always feed bytestrings into the C extension; another option would be that many of the `s` format strings on the C side could be changed into `es` with an explicit `'utf-8'` encoding.

**Comment by koniiiik** [comment] 2016-08-03 16:05
A few moments later we realized that the same thing would happen in `simple_bind` with `who` and `cred` (probably also `bind`, though we don't use that). `who` can be sorted out with the same trick, but `cred` is more difficult to deal with, because it uses the `s#` format string, and `es#` works somewhat differently than other `#`-terminated format strings.

It probably won't be _that_ much work, but since I haven't ever seen either the Python C API, or the libldap API before today, it's beyond my abilities at the moment.

**Comment by rbarrois** [comment] 2016-08-03 22:58
wow, thanks for the help and analysis :-)

I'll have a look soon[ish] into that; but your solution is spot-on.
The issue is that we'll have to check each and every call to libldap functions to detect arguments that are, per the `ldap_*` man pages, UTF-8 text and those that are "raw bytes".

**Comment by ealogar** [comment] 2016-08-22 13:05
I have reproduced the same problem spotted here. Hope to have a sollution soon 💃

**Comment by ealogar** [comment] 2016-08-22 13:20
If we change the default encoding to UTF-8 the issue (in py2x) is fixed, but I don't like too much:

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

**Comment by spaceone** [comment] 2017-02-18 12:48
@ealogar This would break various assumtions applications do.

**Closed as completed** 2017-06-19 00:07 UTC
Labels: bug
